"""Replace the synthetic placeholder photos in samples/evidence/batch-01 with real photos from inbox/photos.

The demo needs eight photos. Each has a role in the expected-results checklist
(samples/expected/batch-01.json), so the real photo must show roughly the same thing.
Some carry a burned-in location stamp because that is what drives the "explicit" tier and
the D-06 "conflict" case; the stamp is drawn onto the copied file, never onto your original.

Usage:
    python3 scripts/adopt_inbox_photos.py --list
    python3 scripts/adopt_inbox_photos.py IMG_2201_L2_corridor_firestop.jpg=inbox/photos/IMG_0012.HEIC \
        IMG_2215.jpg=inbox/photos/IMG_0031.jpg ...

HEIC is converted with macOS `sips`. GPS EXIF is stripped from the copy (the date is kept).
The byte-identical duplicate "IMG_2203_RTU2_anchors (1).jpg" is regenerated automatically.
Nothing in inbox/ is ever committed.
"""
from __future__ import annotations

import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

from PIL import Image, ImageDraw, ImageFont

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "samples" / "evidence" / "batch-01"

# name -> (what the photo must show, stamp burned into the copy or None)
NEEDED = {
    "IMG_2201_L2_corridor_firestop.jpg": ("Fire-stop sealant around a pipe through a wall, product label readable if possible", "L2 corridor outside 210"),
    "IMG_2202_stair1_guard.jpg": ("A stair guard / railing with pickets, NO tape measure in frame", "Stair 1"),
    "IMG_2204_stair1_guard_tape.jpg": ("Same kind of guard with a tape measure held across a picket opening", "Stair 1"),
    "IMG_2203_RTU2_anchors.jpg": ("A rooftop unit or equipment curb with anchor bolts visible", "RTU-2"),
    "firestop_done.jpg": ("Fire-stop sealant around a pipe, nothing in frame that says where it is", None),
    "IMG_2206_L3_firestop.jpg": ("Fire-stop sealant around a smaller conduit through a wall", "L3 corridor firestop"),
    "IMG_2210.jpg": ("Repaired brick / masonry near the ground, no location visible", None),
    "IMG_2215.jpg": ("Anything that is NOT a building element: a truck, a road, a lunch table", None),
}


def _font(size: int):
    for p in ["/System/Library/Fonts/Helvetica.ttc", "/System/Library/Fonts/Supplemental/Arial.ttf"]:
        try:
            return ImageFont.truetype(p, size)
        except Exception:  # noqa: BLE001
            pass
    return ImageFont.load_default()


def _to_jpeg(src: Path) -> Path:
    if src.suffix.lower() in (".heic", ".heif"):
        tmp = Path(tempfile.mkdtemp()) / (src.stem + ".jpg")
        subprocess.run(["sips", "-s", "format", "jpeg", str(src), "--out", str(tmp)], check=True, capture_output=True)
        return tmp
    return src


def adopt(name: str, src: Path) -> None:
    if name not in NEEDED:
        raise SystemExit(f"{name} is not one of the demo photos; run with --list")
    if not src.exists():
        raise SystemExit(f"{src} does not exist")
    _, stamp = NEEDED[name]
    im = Image.open(_to_jpeg(src))
    exif = im.getexif()
    exif.pop(0x8825, None)  # GPS IFD pointer: keep the date, drop the location
    im = im.convert("RGB")
    im.thumbnail((2000, 2000))
    if stamp:
        d = ImageDraw.Draw(im)
        size = max(24, im.width // 40)
        d.text((size, size), stamp, font=_font(size), fill=(255, 255, 255), stroke_width=max(2, size // 12), stroke_fill=(0, 0, 0))
    im.save(OUT / name, "JPEG", quality=88, exif=exif.tobytes())
    print(f"adopted {src.name} -> samples/evidence/batch-01/{name}" + (f" (stamp: {stamp})" if stamp else ""))
    if name == "IMG_2203_RTU2_anchors.jpg":
        shutil.copyfile(OUT / name, OUT / "IMG_2203_RTU2_anchors (1).jpg")
        print("regenerated byte-identical duplicate IMG_2203_RTU2_anchors (1).jpg")


def main(argv: list[str]) -> int:
    if not argv or argv == ["--list"]:
        print("Demo photos needed (name: what to shoot [stamp added to the copy]):")
        for name, (what, stamp) in NEEDED.items():
            print(f"  {name:38} {what}" + (f"  [stamp: {stamp}]" if stamp else ""))
        inbox = ROOT / "inbox" / "photos"
        files = sorted(p.name for p in inbox.glob("*") if p.is_file() and not p.name.startswith("."))
        print(f"\ninbox/photos has {len(files)} file(s)" + (": " + ", ".join(files) if files else ""))
        return 0
    for arg in argv:
        if "=" not in arg:
            raise SystemExit(f"expected NAME=path, got {arg}")
        name, src = arg.split("=", 1)
        adopt(name, Path(src).expanduser())
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
